services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-petshop}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: go-pet-shop
    environment:
      APP_ENV: dev
      DB_TIMEOUT: ${DB_TIMEOUT:-10s}
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-pass}@postgres:5432/${POSTGRES_DB:-petshop}?sslmode=disable
    ports:
      - "8080:8080"
    networks:
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "./migrator --migrations-path ./migrations && ./go-pet-shop"]

volumes:
  postgres_data:

networks:
  monitoring:
    driver: bridge
